#!/bin/bash


# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
  #else
  #exit 0
fi

# Read in the command arguments
case "$1" in
  start)
	echo -n $"Starting services: "
	sudo /usr/local/torque-2.3.0/sbin/qserverd
	echo "[TORQUE] "
	;;
  stop)
	echo -n $"Shutting down services: "
	sudo /usr/local/torque-2.3.0/bin/qterm -t quick
	echo "[TORQUE] "
	;;
  restart)
	$0 stop
	$0 start
	;;
  *)
	echo $"Usage: torque {start|stop|restart}"
	exit 1
esac

exit 0
